<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />



<meta name="progressive" content="false" />
<meta name="allow-skip" content="false" />

<title>Distribution Functions</title>


<!-- highlightjs -->
<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>

<!-- taken from https://github.com/rstudio/rmarkdown/blob/67b7f5fc779e4cfdfd0f021d3d7745b6b6e17149/inst/rmd/h/default.html#L296-L362 -->
<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("section-TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>
<!-- end tabsets -->



</head>

<body>



<div class="pageContent band">
<div class="bandContent page">

<div class="topics">

<div id="section-introduction" class="section level2">
<h2><strong>Introduction</strong></h2>
<p>In this tutorial, you will learn about how to use R’s built in functions for working with distributions. We will specifically be working with the <strong>Normal distribution</strong>, the <strong>binomial distribution</strong>, the <strong>Poisson distribution</strong>, and the <strong>uniform distribution</strong>.</p>
</div>
<div id="section-random-sampling" class="section level2">
<h2><strong>Random sampling</strong></h2>
<p>One crucial component of performing simulations is randomly sampling data from a known distribution. There is a family of functions in R that can perform this task. Today we will discuss <code>rnorm()</code>, <code>rbinom()</code>, <code>rpois()</code>, and <code>runif()</code>.</p>
<p>All these functions operate in a similar way. They require the user to specify:</p>
<ol style="list-style-type: decimal">
<li>The <strong>sample size</strong> to be drawn from the distribution.</li>
<li>The <strong>parameters</strong> of the distribution from which the sample is to be drawn. Sometimes R has default values for these parameters, and other times the function will not run unless the R user specifies their values.</li>
</ol>
<div id="section-rnorm" class="section level3">
<h3><strong><code>rnorm()</code></strong></h3>
<p>Let’s demonstrate the use of one of these functions, <code>rnorm()</code>. <code>rnorm()</code> randomly draws values from the <em>normal distribution</em>.</p>
<p><code>rnorm()</code> has three arguments: <code>n</code>, <code>mean</code>, and <code>sd</code>. <code>n</code> is the <strong>sample size</strong>, while <code>mean</code> and <code>sd</code> are the distribution parameters to be specified (i.e., <span class="math inline">\(\mu\)</span> &amp; <span class="math inline">\(\sigma\)</span>). By default, <code>rnorm()</code> assumes a <code>mean</code> of 0 and a <code>sd</code> of 1.</p>
<pre class="r"><code># randomly draw 10 values from the normal with mean 0 and sd 1
rnorm(n=10)</code></pre>
<pre><code>##  [1]  0.26482888 -0.14320153  0.94612066  0.10885594 -0.57972851 -0.62242425
##  [7] -0.09753893 -1.21245816  0.63962697  0.19580580</code></pre>
<p><code>rnorm()</code> returns a vector of <code>n</code> values randomly drawn from the normal distribution. Above we did not specify the mean or standard deviation, so <code>rnorm()</code> used its default values of 0 and 1 (respectively). 0 and 1 are the default values because they are the mean and standard deviation of the <strong>Standard Normal Distribution</strong>.</p>
<p>Let’s say we want to draw 1000 values from a normal distribution with a mean of 100 and a standard deviation of 15, and plot these values as a histogram. We can easily do so using <code>rnorm()</code>.</p>
<pre class="r"><code># randomly drawing values and saving them in a tibble for easy plotting with ggplot
norm_sim &lt;- tibble(
  value=rnorm(n=1000,mean=100,sd=15)
)
# ggplot 
ggplot(data=norm_sim,aes(x=value))+
  geom_histogram(binwidth = 5,col=&#39;black&#39;,fill=&#39;gray&#39;)</code></pre>
<p><img src="Distribution_Functions_files/figure-html/unnamed-chunk-2-1.png" width="624" /></p>
<p>This function is incredibly useful for simulating data, which will become even more important as you learn more about statistics and modeling. Let’s learn about the other random simulation functions.</p>
</div>
<div id="section-rbinom" class="section level3">
<h3><strong><code>rbinom()</code></strong></h3>
<p><code>rbinom()</code> allows simulation from the <em>binomial distribution</em>. The binomial distribution is a discrete probability distribution, used to model the probability of <em>k</em> successes for a binary event with <em>n</em> trials, where the event has a probability of success of <em>p</em> on a single trial.</p>
<p>For example, a fair coin has a <em>p</em> of .5 of landing on heads on a single flip. If heads is defined as a success (1), and tails is defined as a failure (0), we can use <code>rbinom()</code> to simulate flipping a coin <code>n</code> times. If we tell <code>rbinom()</code> that <code>n=1</code>, <code>size=100</code>, and <code>prob=.5</code>, this is equivalent to the following:</p>
<ul>
<li>Return 1 sample of 100 coin flips (or trials), where there is a .5 probability of heads on a single flip.</li>
</ul>
<pre class="r"><code>flips &lt;- rbinom(n=1,size=100,prob=.5)
flips</code></pre>
<pre><code>## [1] 47</code></pre>
<p>This tells us that when we “flipped” our coin 100 times, we got a sample containing 47 heads (assuming we define 1 as heads and 0 as tails). More generally speaking, our sample contains 47 successes out of 100 (meaning there were 53 failures).</p>
<p>Say we want to do our coin flipping sequence (100 times), 5 separate times. We can use <code>rbinom()</code> but simply change the <code>n</code> argument to 5.</p>
<pre class="r"><code>flips_5 &lt;- rbinom(n=5,size=100,prob=.5)
flips_5</code></pre>
<pre><code>## [1] 50 54 46 54 46</code></pre>
<p>Now, we have 5 samples, each containing various numbers of successes out of 100.</p>
<p>We don’t always have to sample with a .5 probability of success. We can change the <code>prob</code> argument to a different value, indicating a different probability of success on a given trial. After all, not every binary event can be assumed to occur with a 50/50 chance.</p>
<pre class="r"><code>flips_new_prob &lt;- rbinom(n=5, size=100,prob=.2)
flips_new_prob</code></pre>
<pre><code>## [1] 25 20 15 20 16</code></pre>
<p>This new simulation was done assuming only a .2 probability of success, which is reflected in the random samples. Now the numbers of success center around 20, whereas above they centered around 100.</p>
</div>
<div id="section-rpois" class="section level3">
<h3><strong><code>rpois()</code></strong></h3>
<p>Related to the binomial distribution is the <em>Poisson distribution</em>. The Poisson distribution is also a discrete probability distribution, used to model the probability of a particular number events occurring in a given time interval.</p>
<p>For example, say that on average, it rains twice a week in Amherst during the summer (this is not accurate!). We can use the Poisson distribution to model the probability that it rains any particular number of times per week, given that the average frequency is 2. This average frequency is known as <span class="math inline">\(\lambda\)</span> (lambda), the Poisson distribution’s only parameter. Below is a figure demonstrating the Poisson distribution in this scenario:</p>
<p><img src="Distribution_Functions_files/figure-html/unnamed-chunk-6-1.png" width="624" /></p>
<p>As you can see, given that the average frequency of rain is twice per week, it’s fairly likely that it rains anywhere from 0-4 times per week. However, once you go past 4, the probability of 5, 6, 7, etc…rains per week becomes increasingly tiny.</p>
<p>The Poisson distribution is bound by 0 (because we cannot have a negative number of events) and infinity.</p>
<p>Now that we know a bit about the Poisson distribution, we can use the <code>rpois()</code> function to randomly generate data from it.</p>
<p>The <code>rpois()</code> function requires two arguments: <code>n</code> and <code>lambda</code>. <code>n</code> refers to the number of random values to generate, and <code>lambda</code> is the average number of occurrences per time period.</p>
<p>When we run this function, we get random data, with each value corresponding to the number of event occurrences in the time period.</p>
<pre class="r"><code>random_pois &lt;- rpois(n = 10,lambda = 2)
random_pois</code></pre>
<pre><code>##  [1] 1 2 0 2 2 3 1 1 0 1</code></pre>
<p>As with <code>rnorm()</code> and <code>rbinom()</code>, <code>rpois()</code> returns data in the form of a vector.</p>
</div>
<div id="section-runif" class="section level3">
<h3><strong><code>runif()</code></strong></h3>
<p>The <em>uniform distribution</em> is a distribution where all values in a given range are equally likely. For example, if we refer a uniform distribution from 0 to 1, this means that all values from 0 to 1 are equally likely. Note that in this case, we are talking about a <em>continuous uniform distribution</em>, in which there are infinitely many values between 0 and 1 (or whatever the min and max of our range are). There exists a discrete uniform distribution, but this is beyond the scope of the present discussion.</p>
<p><code>runif()</code> requires the argument <code>n</code>, the number of values to sample, as well as the distribution parameters <code>min</code> and <code>max</code>. By default, <code>runif()</code> has a <code>min</code> of 0 and a <code>max</code> of 1.</p>
<p>Running <code>runif(n=10)</code> returns a vector containing 10 values randomly sampled from a uniform distribution from 0 to 1.</p>
<pre class="r"><code># randomly sample 10 values from a uniform distribution from 0 to 1
runif(n=10)</code></pre>
<pre><code>##  [1] 0.74170060 0.43868434 0.51301687 0.23937264 0.47884968 0.34151149
##  [7] 0.49026261 0.81423904 0.03839757 0.63320528</code></pre>
<p>If we specify the <code>min</code> and <code>max</code>, we can change the parameters of the distribution.</p>
<pre class="r"><code># randomly sample 10 values from a uniform distribution from 10 to 100
runif(n=10,min=10,max=100)</code></pre>
<pre><code>##  [1] 61.15694 20.33765 10.64762 67.28167 23.23821 12.75498 73.40792 13.53611
##  [9] 84.62122 63.82492</code></pre>
<p><code>runif()</code> is great for randomly generating numbers when programming. <code>rnorm()</code> can be useful, but by definition certain values are more likely than others. On the other hand, <code>runif()</code> ensures that <em>all values</em> are equally likely (within a range).</p>
</div>
<div id="section-summary---random-sampling-functions" class="section level3">
<h3><strong>Summary - Random Sampling Functions</strong></h3>
<p>You’ve now learned about how to use random sampling functions in R to sample from a normal, binomial, Poisson, and uniform distribution. Here’s a quick key to the functions:</p>
<ul>
<li><code>rnorm()</code> - sample from a normal distribution
<ul>
<li>Arguments:
<ul>
<li><code>n</code> (number of values in the sample)</li>
<li><code>mean</code> (<span class="math inline">\(\mu\)</span>, mean of the distribution, <strong>default value is 0</strong>)</li>
<li><code>sd</code> (<span class="math inline">\(\sigma\)</span>, standard deviation of the distribution, <strong>default value is 1</strong>)</li>
</ul></li>
</ul></li>
<li><code>rbinom()</code> - sample from a binomial distribution
<ul>
<li>Arguments:
<ul>
<li><code>n</code> (number of samples to draw)</li>
<li><code>size</code> (number of trials in each sample, <strong>no default value</strong>)</li>
<li><code>prob</code> (probability of success on a given trial, <strong>no default value</strong>)</li>
</ul></li>
</ul></li>
<li><code>rpois()</code> - sample from a Poisson distribution
<ul>
<li>Arguments:
<ul>
<li><code>n</code> (number of values in the sample)</li>
<li><code>lambda</code> (<span class="math inline">\(\lambda\)</span>, average number of occurences in a given time period, <strong>no default value</strong>)</li>
</ul></li>
</ul></li>
<li><code>runif()</code> - sample from a continuous uniform distribution
<ul>
<li>Arguments:
<ul>
<li><code>n</code> (number of values in the sample)</li>
<li><code>min</code> (lower limit of the distribution, <strong>default value is 0</strong>)</li>
<li><code>max</code> (upper limit of the distribution, <strong>default value is 1</strong>).</li>
</ul></li>
</ul></li>
</ul>
</div>
</div>
<div id="section-probability-massprobability-density" class="section level2">
<h2><strong>Probability Mass/Probability Density</strong></h2>
<p>Yet another family of functions, this time starting with a “d” instead of an “r”, can be used to compute probability mass (in the case of a discrete probability distribution) or probability density (in the case of a continuous probability distribution). Let’s begin with probability mass.</p>
<div id="section-probability-mass" class="section level3">
<h3><strong>Probability Mass</strong></h3>
<p>We can compute probability mass, which essentially tells us, given a distribution, the probability that a random variable is equal to <em>exactly</em> a certain value. Let’s start out by discussing the binomial distribution.</p>
<div id="section-binomial-distribution---dbinom" class="section level4">
<h4>Binomial distribution - <code>dbinom()</code></h4>
<p>Using the function <code>dbinom()</code>, we can compute the probability of a specific number of successes (<code>x</code>), given the number of trials (<code>size</code>) and probability of success on a single trial (<code>prob</code>).</p>
<p>Let’s say we’re flipping a fair coin (i.e., 50% chance of heads and 50% chance of tails). We may want to know the probability that we flip the coin 10 times and get <em>exactly</em> 4 heads.</p>
<pre class="r"><code>dbinom(x=4,size=5,prob=.5)</code></pre>
<pre><code>## [1] 0.15625</code></pre>
<p>There is a 0.15625 probability that we flip a fair coin 10 times and get <em>exactly</em> 4 heads.</p>
<p><code>dbinom()</code> is very useful for finding out the probability of a specific outcome in a sequence of binomial trials. Now let’s move onto the Poisson distribution and <code>dpois()</code>.</p>
<p>Probability mass is very useful. We can use <code>dbinom()</code> to plot the probability of all possible outcomes in a series of binomial trials:</p>
<pre class="r"><code>data_1 &lt;- tibble(
  x = seq(0,10),
  probs = dbinom(x, 10, .5)
) 

ggplot(data_1, aes(x,probs))+
  geom_point()+
  geom_line()+
  scale_x_continuous(breaks = seq(0,10,2))+
  labs(x=&quot;Number of Heads Flipped&quot;,y=&quot;Probability&quot;,title=&quot;Modeling Coin Flip Probability with the Binomial Distribution&quot;)</code></pre>
<p><img src="Distribution_Functions_files/figure-html/unnamed-chunk-11-1.png" width="624" /></p>
</div>
<div id="section-poisson-distribution---dpois" class="section level4">
<h4>Poisson distribution - <code>dpois()</code></h4>
<p>Using <code>dpois()</code>, we can compute the probability of a specific number of occurrences of an event during an interval, given <span class="math inline">\(\lambda\)</span>, the average number of occurrences per interval.</p>
<p>Recall our hypothetical example earlier, where we suggested that on average, it rains 2x per week in Amherst. Given this parameter, we can compute the probability that it rains <em>exactly</em> 3 times in a week. We will use the <code>dpois()</code> function, specifying that <code>x=3</code> and <code>lambda=2</code>.</p>
<pre class="r"><code>dpois(x=3,lambda=2)</code></pre>
<pre><code>## [1] 0.180447</code></pre>
<p>We see that there is a 0.180447 probability of it raining 3 times per week in Amherst, given that on average it rains 2x per week.</p>
<p>Like with <code>dbinom()</code>, we can use <code>dpois()</code> to plot the probability of given outcomes. Though the Poisson distribution is bound only by 0 and infinity, we can plot to a reasonable number of occurrences (at a certain point, values have a probability near 0).</p>
<pre class="r"><code>data_2 &lt;- tibble(
  freqs = 0:10,
  probs = dpois(0:10, 2)
)
ggplot(data_2, aes(freqs,probs))+
  geom_point()+
  geom_line()+
  scale_x_continuous(breaks = seq(0,10,2))+
  scale_y_continuous(limits = c(0,.5),breaks = seq(0,.5,.1))+
  labs(title=&quot;Modeling Rain Frequency Probability with the Poisson Distribution&quot;,
       subtitle = expression(paste(lambda,&quot;= 2&quot;)),
       x=&quot;Rain Frequency per Week&quot;,y=&quot;Probability&quot;)</code></pre>
<p><img src="Distribution_Functions_files/figure-html/unnamed-chunk-13-1.png" width="624" /></p>
</div>
</div>
<div id="section-probability-density" class="section level3">
<h3><strong>Probability Density</strong></h3>
<p>When dealing with continuous distributions, the probability of sampling any specific value is so low as to be near 0. For example, given a normal distribution with mean 10 and sd 2, we could sample 10.1, 10.001, 10.001, and so on…The possibilities are literally infinite!</p>
<p>So with continuous distributions, we compute something related: probability density. Probability density is still the height of the curve, but it is no longer probability - it is density. However, we can still use it to infer which values are more likely. That is, values with a higher density are still more likely to be sampled. Let’s start off by discussing the normal distribution and <code>dnorm()</code>.</p>
<div id="section-normal-distribution---dnorm" class="section level4">
<h4>Normal distribution - <code>dnorm()</code></h4>
<p>Using <code>dnorm()</code>, we can compute probability density for a particular value <code>x</code>, given a normal distribution with a given <code>mean</code> and <code>sd</code>.</p>
<p>Say we have a normal distribution with <code>mean</code> 100 and <code>sd</code> 15. We can compute the probability density for a particular value <code>x</code> as follows:</p>
<pre class="r"><code>dnorm(x=105,mean=100,sd=15)</code></pre>
<pre><code>## [1] 0.02515888</code></pre>
<p>As you can see, the probability density for 105 is very small, despite it being close to the mean.<br />
<code>dnorm()</code> can also be used for plotting the normal distribution. While it’s computationally impossible to compute the density for all possible values, we can simply compute the density for a sequence of integers within a reasonable range for the distribution, and use <code>geom_line()</code> to draw a line between these points.</p>
<pre class="r"><code>data_3 &lt;- tibble(
  x=seq(60,140),
  y=dnorm(seq(60,140),mean=100,sd=15)
)
ggplot(data_3, aes(x,y))+
  geom_line()+
  labs(x=&quot;Value&quot;,y=&quot;Probability Density&quot;,title=&quot;Normal Distribution with Mean 100 and SD 15&quot;)</code></pre>
<p><img src="Distribution_Functions_files/figure-html/unnamed-chunk-15-1.png" width="624" /></p>
<p>As you can see we end up with a smooth normal distribution.</p>
<p>While the probability density for any individual point is low, we can still interpret these values <strong>relative to one another</strong>. By this we mean that points higher on the curve are still more likely than those lower on the curve. For example, it’s more likely to a sample a point within 1 SD of the mean than outside 1 SD of the mean. This is reflected in the height of the curve.</p>
</div>
<div id="section-uniform-distribution---dunif" class="section level4">
<h4>Uniform distribution - <code>dunif()</code></h4>
<p>We can also compute the density for a point on the uniform distribution using <code>dunif()</code>. <code>dunif()</code> requires the point <code>x</code>, as well as the <code>min</code> and <code>max</code> values of the distribution.</p>
<pre class="r"><code>dunif(x=5,min=1,max=10)</code></pre>
<pre><code>## [1] 0.1111111</code></pre>
</div>
</div>
<div id="section-summary---probability-massprobability-density-functions" class="section level3">
<h3><strong>Summary - Probability Mass/Probability Density Functions</strong></h3>
<p>You’ve now learned about how to use probability density and probability mass functions in R. Here’s a quick key to the functions:</p>
<ul>
<li><code>dbinom()</code> - probability mass of point on binomial distribution
<ul>
<li>Arguments:
<ul>
<li><code>x</code> (number of successes)</li>
<li><code>size</code> (number of trials, <strong>no default value</strong>)</li>
<li><code>prob</code> (probability of success on a given trial, <strong>no default value</strong>)</li>
</ul></li>
</ul></li>
<li><code>dpois()</code> - probability mass of point on Poisson distribution
<ul>
<li>Arguments:
<ul>
<li><code>x</code> (number of occurences)</li>
<li><code>lambda</code> (<span class="math inline">\(\lambda\)</span>, average number of occurences in a given time period, <strong>no default value</strong>)<br />
</li>
</ul></li>
</ul></li>
<li><code>dnorm()</code> - density of point on normal distribution
<ul>
<li>Arguments:
<ul>
<li><code>x</code> (value to get density of)</li>
<li><code>mean</code> (<span class="math inline">\(\mu\)</span>, mean of the distribution, <strong>default value is 0</strong>)</li>
<li><code>sd</code> (<span class="math inline">\(\sigma\)</span>, standard deviation of the distribution, <strong>default value is 1</strong>)</li>
</ul></li>
</ul></li>
<li><code>dunif()</code> - density of point on continuous uniform distribution
<ul>
<li>Arguments:
<ul>
<li><code>x</code> (value to get density of)</li>
<li><code>min</code> (lower limit of the distribution, <strong>default value is 0</strong>)</li>
<li><code>max</code> (upper limit of the distribution, <strong>default value is 1</strong>).</li>
</ul></li>
</ul></li>
</ul>
</div>
</div>
<div id="section-cumulative-probability" class="section level2">
<h2><strong>Cumulative probability</strong></h2>
<p>Cumulative probability allows to get the probability of a <em>range</em> of values. In R, these functions begin with a “p” (i.e., <code>pnorm()</code>, <code>pbinom()</code>, <code>ppois()</code>, and <code>punif()</code>). Let’s start off by discussing <code>pnorm()</code>.</p>
<div id="section-pnorm" class="section level3">
<h3><strong><code>pnorm()</code></strong></h3>
<p>Using <code>pnorm()</code>, we can get the probability of sampling a value less than or equal to a given value, as well as greater than or equal to a given value.</p>
<p><img src="Distribution_Functions_files/figure-html/unnamed-chunk-17-1.png" width="624" /></p>
<p>Here, we have a normal distribution with mean 100 and sd 15. We also plotted a red line at 95 on the x axis. Imagine we want to find the probability of sampling a value of 95 or less (anything to the <strong>left</strong> of the red line). We can do so using <code>pnorm()</code>, specifying the point with <code>q</code>, as well as the <code>mean</code> and <code>sd</code> of the distribution.</p>
<pre class="r"><code>pnorm(q=95, mean=100, sd=15)</code></pre>
<pre><code>## [1] 0.3694413</code></pre>
<p>There is a 0.3694413 probability of sampling a value of <strong>95 or less</strong> from a normal distribution with mean 100 and sd 15.</p>
<p>What about if we want to find the probability of sampling a value to the <strong>right</strong> of 95? We can simply include the argument <code>lower.tail=F</code> (<code>lower.tail=T</code> by default, indicating that it always assumes the user is asking for the left side of the curve unless otherwise specified).</p>
<pre class="r"><code>pnorm(q=95, mean=100, sd=15,lower.tail = F)</code></pre>
<pre><code>## [1] 0.6305587</code></pre>
<p>There is a 0.6305587 probability of sampling a value of <strong>95 or greater</strong> from a normal distribution with mean 100 and sd 15.</p>
<p>One final point about <code>pnorm()</code>. What do you think happens when we add these two probabilities together?</p>
<pre class="r"><code>pnorm(q=95, mean=100, sd=15)+pnorm(q=95, mean=100, sd=15,lower.tail = F)</code></pre>
<pre><code>## [1] 1</code></pre>
<p>We get a probability of 1! This is because there is a 100% chance of sampling a value <em>less or equal to 95</em> <strong>OR</strong> <em>greater than or equal to 95</em>. In other words, there is a 100% chance of sampling a value between <span class="math inline">\(-\infty\)</span> and <span class="math inline">\(\infty\)</span>.</p>
</div>
<div id="section-pbinom" class="section level3">
<h3><strong><code>pbinom()</code></strong></h3>
<p>We can perform a similar operation on the binomial distribution using <code>pbinom()</code>. We simply need to specify the point <code>q</code> as well as the number of trials (<code>size</code>) and probability of success on a single trial (<code>prob</code>).</p>
<p>For example, say you want to know the probability of flipping 4 or less heads out of 10 flips, using a fair coin. You can find this probability using <code>pbinom()</code>:</p>
<pre class="r"><code>pbinom(q=4,size=10,prob=.5)</code></pre>
<pre><code>## [1] 0.3769531</code></pre>
<p><code>pbinom()</code> also has <code>lower.tail=T</code> by default. So to find the probability of 4 or greater heads, we can include <code>lower.tail=F</code>.</p>
<pre class="r"><code>pbinom(q=4,size=10,prob=.5,lower.tail = F)</code></pre>
<pre><code>## [1] 0.6230469</code></pre>
<p>Again, when we add these two probabilities together, we should expect to get a value of 1.</p>
<pre class="r"><code>pbinom(q=4,size=10,prob=.5)+pbinom(q=4,size=10,prob=.5,lower.tail = F)</code></pre>
<pre><code>## [1] 1</code></pre>
<p>We also get a value of 1 if we set <code>q</code> equal to the number of trials.</p>
<pre class="r"><code>pbinom(q=10,size=10,prob=.5)</code></pre>
<pre><code>## [1] 1</code></pre>
<p>This makes sense because there’s a 100% chance of flipping a coin 10 times and getting 10 or fewer heads. In other words, this <strong>exhausts</strong> all possibilities.</p>
</div>
<div id="section-ppois" class="section level3">
<h3><strong><code>ppois()</code></strong></h3>
<p>We can use <code>ppois()</code> to calculate cumulative probability for a Poisson distribution.</p>
<p>Again going back to our rain example, say we want to know the probability of it raining 1 or fewer times in a week, given that on average it rains 2x per week. We can simply run <code>ppois()</code> with <code>q=1</code> and <code>lambda=2</code>.</p>
<pre class="r"><code>ppois(q=1,lambda=2)</code></pre>
<pre><code>## [1] 0.4060058</code></pre>
<p>Just as with <code>dnorm()</code> and <code>dbinom()</code>, to find the probability of 1 or more occurrences, we simply set <code>lower.tail=F</code>.</p>
<pre class="r"><code>ppois(q=1,lambda=2,lower.tail=F)</code></pre>
<pre><code>## [1] 0.5939942</code></pre>
<p>Again, these two probabilities sum to 1.</p>
<pre class="r"><code>ppois(q=1,lambda=2)+ppois(q=1,lambda=2,lower.tail=F)</code></pre>
<pre><code>## [1] 1</code></pre>
<p>It’s also important to note than when setting <code>lower.tail=F</code> with <code>ppois()</code>, we calculate the probability from <code>q</code> to <span class="math inline">\(\infty\)</span>, as the Poisson distribution is bound by 0 on the left and <span class="math inline">\(\infty\)</span> on the right.</p>
</div>
<div id="section-punif" class="section level3">
<h3><strong><code>punif()</code></strong></h3>
<p>Lastly, we can use <code>punif()</code> to calculate cumulative probability with the uniform distribution.</p>
<pre class="r"><code>punif(q=10,min=0,max=30)</code></pre>
<pre><code>## [1] 0.3333333</code></pre>
<p>Above, we calculate the cumulative probability from 10 to the lower limit (0).</p>
<p>We can also calculate the cumulative probability from 10 to the upper limit (30).</p>
<pre class="r"><code>punif(q=10,min=0,max=30,lower.tail=F)</code></pre>
<pre><code>## [1] 0.6666667</code></pre>
<p>And again, these two probabilities will sum to 1.</p>
<pre class="r"><code>punif(q=10,min=0,max=30)+punif(q=10,min=0,max=30,lower.tail=F)</code></pre>
<pre><code>## [1] 1</code></pre>
</div>
<div id="section-summary---cumulative-probability-functions" class="section level3">
<h3><strong>Summary - Cumulative Probability Functions</strong></h3>
<p>You’ve now learned about how to use probability density and probability mass functions in R. Here’s a quick key to the functions:</p>
<ul>
<li><code>pnorm()</code> - cumulative probability of normal distribution
<ul>
<li>Arguments:
<ul>
<li><code>q</code> (point to get cumulative probability of)</li>
<li><code>mean</code> (<span class="math inline">\(\mu\)</span>, mean of the distribution, <strong>default value is 0</strong>)</li>
<li><code>sd</code> (<span class="math inline">\(\sigma\)</span>, standard deviation of the distribution, <strong>default value is 1</strong>)<br />
</li>
</ul></li>
</ul></li>
<li><code>pbinom()</code> - cumulative probability of binomial distribution
<ul>
<li>Arguments:
<ul>
<li><code>q</code> (point to get cumulative probability of)</li>
<li><code>size</code> (number of trials, <strong>no default value</strong>)</li>
<li><code>prob</code> (probability of success on a given trial, <strong>no default value</strong>)</li>
</ul></li>
</ul></li>
<li><code>ppois()</code> - cumulative probability of point on Poisson distribution
<ul>
<li>Arguments:
<ul>
<li><code>q</code> (point to get cumulative probability of)</li>
<li><code>lambda</code> (<span class="math inline">\(\lambda\)</span>, average number of occurrences in a given time period, <strong>no default value</strong>)<br />
</li>
</ul></li>
</ul></li>
<li><code>punif()</code> - cumulative probability of point on continuous uniform distribution
<ul>
<li>Arguments:
<ul>
<li><code>q</code> (point to get cumulative probability of)</li>
<li><code>min</code> (lower limit of the distribution, <strong>default value is 0</strong>)</li>
<li><code>max</code> (upper limit of the distribution, <strong>default value is 1</strong>).</li>
</ul></li>
</ul></li>
</ul>
</div>
</div>
<div id="section-quantile-functions" class="section level2">
<h2><strong>Quantile functions</strong></h2>
<p>The last family of functions to discuss is the quantile functions. These functions begin with a “q”, and we use them when we want to find the specific value on a distribution associated with a particular cumulative probability.</p>
<div id="section-qnorm" class="section level3">
<h3><strong><code>qnorm()</code></strong></h3>
<p>Say we want to find the point on the standard normal distribution where 5% of the distribution is to the left (for example, finding the cutoff value for a z-test). You can do so easily using <code>qnorm()</code>, simply specifying <code>p=.05</code>.</p>
<pre class="r"><code>qnorm(p=.05)</code></pre>
<pre><code>## [1] -1.644854</code></pre>
<p>You can also specify the <code>mean</code> and <code>sd</code> of the distribution.</p>
<pre class="r"><code>qnorm(p=.05,mean=100,sd=15)</code></pre>
<pre><code>## [1] 75.3272</code></pre>
<p>We see that 5% of the normal distribution (with mean 100 and sd 15) is to the left of 75.3271956.</p>
<p>We can also change the side of the distribution we look at by changing the argument <code>lower.tail</code> to <code>FALSE</code>.</p>
<pre class="r"><code>qnorm(p=.05,mean=100,sd=15,lower.tail=FALSE)</code></pre>
<pre><code>## [1] 124.6728</code></pre>
<p>This gives us the point where 5% of the distribution is to the <strong>RIGHT</strong>.</p>
</div>
<div id="section-qbinom" class="section level3">
<h3><strong><code>qbinom()</code></strong></h3>
<p><code>qbinom()</code> works similarly. We simply input a cumulative probability value with the <code>p</code> argument and specify the parameters to the distribution (<code>size</code> and <code>prob</code>).</p>
<pre class="r"><code>qbinom(p=.05,size=10,prob=.5)</code></pre>
<pre><code>## [1] 2</code></pre>
<p>This tells us that 5% of the binomial distribution (with 10 trials and probability of .5 on a single trial) is to the left of 2.</p>
</div>
<div id="section-qpois" class="section level3">
<h3><strong><code>qpois()</code></strong></h3>
<p>Again, with <code>qpois()</code>, we input a cumulative probability value and in return get a point on the distribution. We also specify the Poisson distribution parameter <code>lambda</code>.</p>
<pre class="r"><code>qpois(p=.5,lambda=2)</code></pre>
<pre><code>## [1] 2</code></pre>
<p>This tells us that 50% of the Poisson distribution (with <code>lambda</code> equal to 2) is to the left of 0.</p>
</div>
<div id="section-qunif" class="section level3">
<h3><strong><code>qunif()</code></strong></h3>
<p>With <code>qunif()</code>, we input a cumulative probability value and in return get a point on the distribution. We also specify the <code>min</code> and <code>max</code> of the distribution.</p>
<pre class="r"><code>qunif(p=.05, min=10,max=40)</code></pre>
<pre><code>## [1] 11.5</code></pre>
</div>
<div id="section-summary---quantile-functions" class="section level3">
<h3><strong>Summary - Quantile Functions</strong></h3>
<p>You’ve now learned about how to use probability density and probability mass functions in R. Here’s a quick key to the functions:</p>
<ul>
<li><code>qnorm()</code> - quantile on normal distribution
<ul>
<li>Arguments:
<ul>
<li><code>p</code> (cumulative probability to get quantile for)</li>
<li><code>mean</code> (<span class="math inline">\(\mu\)</span>, mean of the distribution, <strong>default value is 0</strong>)</li>
<li><code>sd</code> (<span class="math inline">\(\sigma\)</span>, standard deviation of the distribution, <strong>default value is 1</strong>)<br />
</li>
</ul></li>
</ul></li>
<li><code>qbinom()</code> - quantile on binomial distribution
<ul>
<li>Arguments:
<ul>
<li><code>p</code> (cumulative probability to get quantile for)</li>
<li><code>size</code> (number of trials, <strong>no default value</strong>)</li>
<li><code>prob</code> (probability of success on a given trial, <strong>no default value</strong>)</li>
</ul></li>
</ul></li>
<li><code>qpois()</code> - quantile on Poisson distribution
<ul>
<li>Arguments:
<ul>
<li><code>p</code> (cumulative probability to get quantile for)</li>
<li><code>lambda</code> (<span class="math inline">\(\lambda\)</span>, average number of occurrences in a given time period, <strong>no default value</strong>)<br />
</li>
</ul></li>
</ul></li>
<li><code>qunif()</code> - quantile on continuous uniform distribution
<ul>
<li>Arguments:
<ul>
<li><code>p</code> (cumulative probability to get quantile for)</li>
<li><code>min</code> (lower limit of the distribution, <strong>default value is 0</strong>)</li>
<li><code>max</code> (upper limit of the distribution, <strong>default value is 1</strong>).</li>
</ul></li>
</ul></li>
</ul>
</div>
</div>
<div id="section-which-function-should-i-use" class="section level2">
<h2><strong>Which function should I use?</strong></h2>
<p>Many students often have difficulty determining which function to use. Below is a flowchart meant to aid in the decision process:</p>
<p><img src="Distribution_Functions_files/figure-html/unnamed-chunk-37-1.png" width="624" /></p>
</div>
<div id="section-conclusion" class="section level2">
<h2><strong>Conclusion</strong></h2>
In this tutorial, you learned about the distribution functions associated with the normal, uniform, binomial, and Poisson distributions.<br />

<script type="application/shiny-prerendered" data-context="server-start">
library(learnr)
library(tidyverse)
library(knitr)
library(png)
library(grid)
which_function <- readPNG('which_function.png')
opts_chunk$set(echo = TRUE)
tutorial_options(exercise.timelimit = 10)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::register_http_handlers(session, metadata = NULL)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
session$onSessionEnded(function() {
        learnr:::session_stop_event(session)
      })
</script>
 <!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["header-attrs"]},{"type":"character","attributes":{},"value":["2.11"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pandoc"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["header-attrs.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.11"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["3.6.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/3.6.0"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery-3.6.0.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquerylib"]},{"type":"logical","attributes":{},"value":[true]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootstrap"]},{"type":"character","attributes":{},"value":["3.3.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/bootstrap"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["viewport"]}},"value":[{"type":"character","attributes":{},"value":["width=device-width, initial-scale=1"]}]},{"type":"character","attributes":{},"value":["js/bootstrap.min.js","shim/html5shiv.min.js","shim/respond.min.js"]},{"type":"character","attributes":{},"value":["css/cerulean.min.css"]},{"type":"character","attributes":{},"value":["<style>h1 {font-size: 34px;}\n       h1.title {font-size: 38px;}\n       h2 {font-size: 30px;}\n       h3 {font-size: 24px;}\n       h4 {font-size: 18px;}\n       h5 {font-size: 16px;}\n       h6 {font-size: 12px;}\n       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}\n       pre:not([class]) { background-color: white }<\/style>"]},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.11"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["pagedtable"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pagedtable-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["js/pagedtable.js"]},{"type":"character","attributes":{},"value":["css/pagedtable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.11"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["textmate.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.11"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-format"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmarkdown/templates/tutorial/resources"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-format.js"]},{"type":"character","attributes":{},"value":["tutorial-format.css","rstudio-theme.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["3.6.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/3.6.0"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery-3.6.0.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquerylib"]},{"type":"logical","attributes":{},"value":[true]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["navigation"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/navigation-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tabsets.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.11"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["default.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.11"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["3.6.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/3.6.0"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery-3.6.0.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquerylib"]},{"type":"logical","attributes":{},"value":[true]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["font-awesome"]},{"type":"character","attributes":{},"value":["5.1.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/fontawesome"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["css/all.css","css/v4-shims.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.11"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootbox"]},{"type":"character","attributes":{},"value":["4.4.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/bootbox"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["bootbox.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["idb-keyvalue"]},{"type":"character","attributes":{},"value":["3.2.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/idb-keyval"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["idb-keyval-iife-compat.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[false]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages"]}},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages","version"]},"class":{"type":"character","attributes":{},"value":["data.frame"]},"row.names":{"type":"integer","attributes":{},"value":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87]}},"value":[{"type":"character","attributes":{},"value":["assertthat","backports","base","broom","bslib","cachem","cellranger","cli","colorspace","compiler","crayon","datasets","DBI","dbplyr","digest","dplyr","ellipsis","evaluate","fansi","farver","fastmap","forcats","fs","generics","ggplot2","glue","graphics","grDevices","grid","gtable","haven","highr","hms","htmltools","htmlwidgets","httpuv","httr","jquerylib","jsonlite","knitr","labeling","later","learnr","lifecycle","lubridate","magrittr","markdown","methods","mime","modelr","munsell","pillar","pkgconfig","png","promises","purrr","R6","Rcpp","readr","readxl","reprex","rlang","rmarkdown","rprojroot","rstudioapi","rvest","sass","scales","shiny","stats","stringi","stringr","tibble","tidyr","tidyselect","tidyverse","tools","truncnorm","tzdb","utf8","utils","vctrs","withr","xfun","xml2","xtable","yaml"]},{"type":"character","attributes":{},"value":["0.2.1","1.4.1","4.1.0","0.7.12","0.2.5.1","1.0.6","1.1.0","3.1.1","2.0-2","4.1.0","1.4.2","4.1.0","1.1.2","2.1.1","0.6.29","1.0.7","0.3.2","0.14","1.0.2","2.1.0","1.1.0","0.5.1","1.5.2","0.1.1","3.3.5","1.6.1","4.1.0","4.1.0","4.1.0","0.3.0","2.4.3","0.9","1.1.1","0.5.2","1.5.3","1.6.1","1.4.2","0.1.4","1.7.3","1.37","0.4.2","1.3.0","0.10.1","1.0.1","1.8.0","2.0.2","1.1","4.1.0","0.12","0.1.8","0.5.0","1.6.5","2.0.3","0.1-7","1.2.0.1","0.3.4","2.5.1","1.0.8","2.1.2","1.3.1","2.0.1","1.0.0","2.11","2.0.2","0.13","1.0.2","0.4.0","1.1.1","1.6.0","4.1.0","1.7.6","1.4.0","3.1.6","1.1.4","1.1.1","1.3.1","4.1.0","1.0-8","0.2.0","1.2.2","4.1.0","0.3.8","2.4.3","0.29","1.3.3","1.8-4","2.2.2"]}]}]}
</script>
<!--/html_preserve-->
</div>

</div> <!-- topics -->

<div class="topicsContainer">
<div class="topicsPositioner">
<div class="band">
<div class="bandContent topicsListContainer">

<!-- begin doc-metadata -->
<div id="doc-metadata">
<h2 class="title toc-ignore" style="display:none;">Distribution Functions</h2>
</div>
<!-- end doc-metadata -->

</div> <!-- bandContent.topicsListContainer -->
</div> <!-- band -->
</div> <!-- topicsPositioner -->
</div> <!-- topicsContainer -->


</div> <!-- bandContent page -->
</div> <!-- pageContent band -->




<script>
// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>


</body>

</html>
